// <auto-generated />
using System;
using Canalog.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Canalog.Infrastructure.Migrations
{
    [DbContext(typeof(EventDbContext))]
    [Migration("20251215215323_NewThemesWithBackground")]
    partial class NewThemesWithBackground
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Canalog.Domain.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("End")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Canalog.Domain.Models.EventColorScheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Blue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Green")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purple")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Red")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yellow")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EventColorSchemes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccc0000-eeee-4eee-8eee-000000000111"),
                            Blue = "#3B82F6",
                            Green = "#22C55E",
                            Purple = "#8B5CF6",
                            Red = "#EF4444",
                            Yellow = "#EAB308"
                        },
                        new
                        {
                            Id = new Guid("dddd0000-ffff-4fff-8fff-000000000222"),
                            Blue = "#60A5FA",
                            Green = "#4ADE80",
                            Purple = "#A78BFA",
                            Red = "#F87171",
                            Yellow = "#FACC15"
                        },
                        new
                        {
                            Id = new Guid("11111111-eeee-4eee-8eee-111111111111"),
                            Blue = "#3E6E95",
                            Green = "#4C9A53",
                            Purple = "#6A4E82",
                            Red = "#A24444",
                            Yellow = "#C7B66D"
                        },
                        new
                        {
                            Id = new Guid("22222222-ffff-4fff-8fff-222222222222"),
                            Blue = "#9EB7F3",
                            Green = "#A8E6C6",
                            Purple = "#C39AED",
                            Red = "#E09AA7",
                            Yellow = "#F7E7A5"
                        },
                        new
                        {
                            Id = new Guid("33333333-aaaa-4aaa-8aaa-333333333333"),
                            Blue = "#00C8F0",
                            Green = "#2DE07B",
                            Purple = "#B24CFF",
                            Red = "#FF3366",
                            Yellow = "#FFD739"
                        },
                        new
                        {
                            Id = new Guid("44444444-bbbb-4bbb-8bbb-444444444444"),
                            Blue = "#45A6FD",
                            Green = "#2FDE9E",
                            Purple = "#B07BFF",
                            Red = "#FF4F6D",
                            Yellow = "#FADF6A"
                        },
                        new
                        {
                            Id = new Guid("55555555-cccc-4ccc-8ccc-555555555555"),
                            Blue = "#7FA7BF",
                            Green = "#9DBF7A",
                            Purple = "#A68CAF",
                            Red = "#C7654E",
                            Yellow = "#D7C678"
                        },
                        new
                        {
                            Id = new Guid("66666666-dddd-4ddd-8ddd-666666666666"),
                            Blue = "#5779FF",
                            Green = "#2BFF78",
                            Purple = "#D33BFF",
                            Red = "#FF2B2B",
                            Yellow = "#FFD02C"
                        },
                        new
                        {
                            Id = new Guid("77777777-eeee-4eee-8eee-777777777777"),
                            Blue = "#4E9CE6",
                            Green = "#5EC97A",
                            Purple = "#A47CCD",
                            Red = "#C95E5E",
                            Yellow = "#E6D45A"
                        },
                        new
                        {
                            Id = new Guid("88888888-eeee-4eee-8eee-888888888222"),
                            Blue = "#3AB8FF",
                            Green = "#38E8A4",
                            Purple = "#C07CFF",
                            Red = "#FF5A7A",
                            Yellow = "#FFC85A"
                        },
                        new
                        {
                            Id = new Guid("99999999-ffff-4fff-8fff-999999999222"),
                            Blue = "#6DA4FF",
                            Green = "#77E5C2",
                            Purple = "#C07BFF",
                            Red = "#FF7AA3",
                            Yellow = "#FFE072"
                        },
                        new
                        {
                            Id = new Guid("aaaa0000-dddd-4ddd-8ddd-a00000000022"),
                            Blue = "#5A93C9",
                            Green = "#5EC46A",
                            Purple = "#A64CC7",
                            Red = "#E44733",
                            Yellow = "#F7CF47"
                        },
                        new
                        {
                            Id = new Guid("bbbb0000-dddd-4ddd-8ddd-b00000000022"),
                            Blue = "#4E9CD6",
                            Green = "#4AD47F",
                            Purple = "#A886D6",
                            Red = "#D96A68",
                            Yellow = "#F0DE67"
                        });
                });

            modelBuilder.Entity("Canalog.Domain.Models.UiColorScheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Accent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CenterFill")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CenterStroke")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClockHandPrimary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClockHandSecondary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlassHighlight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlassShadow")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextPrimary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextSecondary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TickPrimary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TickSecondary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UiColorSchemes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccc0000-aaaa-4aaa-8aaa-000000000011"),
                            Accent = "#3B82F6",
                            BackgroundColor = "#FFFFFF",
                            CenterFill = "#FFFFFF",
                            CenterStroke = "#1A1A1A",
                            ClockHandPrimary = "#1A1A1A",
                            ClockHandSecondary = "#5F6368",
                            GlassHighlight = "rgba(255,255,255,0.85)",
                            GlassShadow = "rgba(0,0,0,0.12)",
                            TextPrimary = "#1A1A1A",
                            TextSecondary = "#5F6368",
                            TickPrimary = "#1A1A1A",
                            TickSecondary = "#C7C7C7"
                        },
                        new
                        {
                            Id = new Guid("dddd0000-bbbb-4bbb-8bbb-000000000022"),
                            Accent = "#22D3EE",
                            BackgroundColor = "#0F1115",
                            CenterFill = "#0F1115",
                            CenterStroke = "#EDEDED",
                            ClockHandPrimary = "#EDEDED",
                            ClockHandSecondary = "#9AA0A6",
                            GlassHighlight = "rgba(255,255,255,0.10)",
                            GlassShadow = "rgba(0,0,0,0.65)",
                            TextPrimary = "#EDEDED",
                            TextSecondary = "#9AA0A6",
                            TickPrimary = "#EDEDED",
                            TickSecondary = "#3A3F45"
                        },
                        new
                        {
                            Id = new Guid("11111111-aaaa-4aaa-8aaa-111111111111"),
                            Accent = "#88B48D",
                            BackgroundColor = "#C7D9C5",
                            CenterFill = "#2E4A2F",
                            CenterStroke = "#1B331C",
                            ClockHandPrimary = "#1E3A1F",
                            ClockHandSecondary = "#2F5A30",
                            GlassHighlight = "rgba(255,255,255,0.35)",
                            GlassShadow = "rgba(20,40,20,0.35)",
                            TextPrimary = "#1E3A1F",
                            TextSecondary = "#4A6B4C",
                            TickPrimary = "#2C4C2D",
                            TickSecondary = "#7EA884"
                        },
                        new
                        {
                            Id = new Guid("22222222-bbbb-4bbb-8bbb-222222222222"),
                            Accent = "#F4B2C7",
                            BackgroundColor = "#F3EAF7",
                            CenterFill = "#7E6FB6",
                            CenterStroke = "#5C4A92",
                            ClockHandPrimary = "#5A4D7A",
                            ClockHandSecondary = "#7B6CA8",
                            GlassHighlight = "rgba(255,255,255,0.50)",
                            GlassShadow = "rgba(120,100,160,0.28)",
                            TextPrimary = "#5A4D7A",
                            TextSecondary = "#A28CC2",
                            TickPrimary = "#6A5E93",
                            TickSecondary = "#B8A7D6"
                        },
                        new
                        {
                            Id = new Guid("33333333-cccc-4ccc-8ccc-333333333333"),
                            Accent = "#FF4BC2",
                            BackgroundColor = "#1A1A26",
                            CenterFill = "#FFD766",
                            CenterStroke = "#CCAA44",
                            ClockHandPrimary = "#FF4BC2",
                            ClockHandSecondary = "#FFD766",
                            GlassHighlight = "rgba(255,255,255,0.25)",
                            GlassShadow = "rgba(0,0,0,0.45)",
                            TextPrimary = "#FFFFFF",
                            TextSecondary = "#D2D2D2",
                            TickPrimary = "#FFFFFF",
                            TickSecondary = "#A1A1A1"
                        },
                        new
                        {
                            Id = new Guid("44444444-dddd-4ddd-8ddd-444444444444"),
                            Accent = "#7FE5DB",
                            BackgroundColor = "#0E1B1A",
                            CenterFill = "#0D4F4F",
                            CenterStroke = "#0B3636",
                            ClockHandPrimary = "#CFFDFE",
                            ClockHandSecondary = "#68C8C8",
                            GlassHighlight = "rgba(255,255,255,0.20)",
                            GlassShadow = "rgba(0,0,0,0.55)",
                            TextPrimary = "#CFFDFE",
                            TextSecondary = "#8ED3D9",
                            TickPrimary = "#C8F4F4",
                            TickSecondary = "#6ABEBE"
                        },
                        new
                        {
                            Id = new Guid("55555555-eeee-4eee-8eee-555555555555"),
                            Accent = "#CBA76F",
                            BackgroundColor = "#E3C9A8",
                            CenterFill = "#8E6B48",
                            CenterStroke = "#5B4029",
                            ClockHandPrimary = "#4E3A28",
                            ClockHandSecondary = "#A07852",
                            GlassHighlight = "rgba(255,255,255,0.22)",
                            GlassShadow = "rgba(60,40,20,0.35)",
                            TextPrimary = "#4E3A28",
                            TextSecondary = "#8E745D",
                            TickPrimary = "#4E3A28",
                            TickSecondary = "#A88C6E"
                        },
                        new
                        {
                            Id = new Guid("66666666-ffff-4fff-8fff-666666666666"),
                            Accent = "#FF6A4A",
                            BackgroundColor = "#1A0000",
                            CenterFill = "#FF1A1A",
                            CenterStroke = "#B30000",
                            ClockHandPrimary = "#FF6A4A",
                            ClockHandSecondary = "#FF4545",
                            GlassHighlight = "rgba(255,255,255,0.20)",
                            GlassShadow = "rgba(255,0,0,0.35)",
                            TextPrimary = "#FFDADA",
                            TextSecondary = "#EBA0A0",
                            TickPrimary = "#FFE0E0",
                            TickSecondary = "#FF9C9C"
                        },
                        new
                        {
                            Id = new Guid("77777777-aaaa-4aaa-8aaa-777777777777"),
                            Accent = "#53C49A",
                            BackgroundColor = "#F3EDE3",
                            CenterFill = "#3C6A50",
                            CenterStroke = "#244434",
                            ClockHandPrimary = "#2F503C",
                            ClockHandSecondary = "#4FA781",
                            GlassHighlight = "rgba(255,255,255,0.35)",
                            GlassShadow = "rgba(40,70,50,0.25)",
                            TextPrimary = "#2F503C",
                            TextSecondary = "#6A8F77",
                            TickPrimary = "#2F503C",
                            TickSecondary = "#90B8A0"
                        },
                        new
                        {
                            Id = new Guid("88888888-aaaa-4aaa-8aaa-888888888111"),
                            Accent = "#FF7DE3",
                            BackgroundColor = "#0A1C25",
                            CenterFill = "#FFB75E",
                            CenterStroke = "#CC8E3C",
                            ClockHandPrimary = "#57D5FF",
                            ClockHandSecondary = "#57D5FF",
                            GlassHighlight = "rgba(255,255,255,0.25)",
                            GlassShadow = "rgba(0,0,0,0.55)",
                            TextPrimary = "#E6F7FF",
                            TextSecondary = "#9AC6D9",
                            TickPrimary = "#D6F3FF",
                            TickSecondary = "#7ECDE4"
                        },
                        new
                        {
                            Id = new Guid("99999999-bbbb-4bbb-8bbb-999999999111"),
                            Accent = "#CB8FFF",
                            BackgroundColor = "#0D0A24",
                            CenterFill = "#7C4BFF",
                            CenterStroke = "#4E2BBF",
                            ClockHandPrimary = "#ECE6FF",
                            ClockHandSecondary = "#A883FF",
                            GlassHighlight = "rgba(255,255,255,0.22)",
                            GlassShadow = "rgba(40,0,80,0.45)",
                            TextPrimary = "#ECE6FF",
                            TextSecondary = "#B8A9E6",
                            TickPrimary = "#EFE8FF",
                            TickSecondary = "#B9A4FF"
                        },
                        new
                        {
                            Id = new Guid("aaaa0000-cccc-4ccc-8ccc-a00000000011"),
                            Accent = "#E86F1A",
                            BackgroundColor = "#F2D27A",
                            CenterFill = "#C24F33",
                            CenterStroke = "#8C3A24",
                            ClockHandPrimary = "#4B2A24",
                            ClockHandSecondary = "#B03C2E",
                            GlassHighlight = "rgba(255,255,255,0.32)",
                            GlassShadow = "rgba(100,50,20,0.35)",
                            TextPrimary = "#4B2A24",
                            TextSecondary = "#7F4A3E",
                            TickPrimary = "#4B2A24",
                            TickSecondary = "#D9A563"
                        },
                        new
                        {
                            Id = new Guid("bbbb0000-cccc-4ccc-8ccc-b00000000011"),
                            Accent = "#59EBA4",
                            BackgroundColor = "#0A1F0E",
                            CenterFill = "#1D5E32",
                            CenterStroke = "#123D21",
                            ClockHandPrimary = "#CFFFE1",
                            ClockHandSecondary = "#4EC47E",
                            GlassHighlight = "rgba(255,255,255,0.20)",
                            GlassShadow = "rgba(0,40,10,0.40)",
                            TextPrimary = "#CFFFE1",
                            TextSecondary = "#86D9A8",
                            TickPrimary = "#CFFFE1",
                            TickSecondary = "#89D2A2"
                        });
                });

            modelBuilder.Entity("Canalog.Domain.Options", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ThemeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TimeFormat")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ThemeId");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("Canalog.Domain.Theme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Background")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EventColorSchemeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UiColorSchemeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EventColorSchemeId");

                    b.HasIndex("UiColorSchemeId");

                    b.ToTable("Themes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-111111111111"),
                            Background = "src/assets/images/leafs.png",
                            EventColorSchemeId = new Guid("11111111-eeee-4eee-8eee-111111111111"),
                            Name = "Leaf Forest",
                            UiColorSchemeId = new Guid("11111111-aaaa-4aaa-8aaa-111111111111")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-4222-8222-222222222222"),
                            Background = "src/assets/images/clouds.png",
                            EventColorSchemeId = new Guid("22222222-ffff-4fff-8fff-222222222222"),
                            Name = "Pastel Clouds",
                            UiColorSchemeId = new Guid("22222222-bbbb-4bbb-8bbb-222222222222")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-4333-8333-333333333333"),
                            Background = "src/assets/images/color-burst.png",
                            EventColorSchemeId = new Guid("33333333-aaaa-4aaa-8aaa-333333333333"),
                            Name = "Color Burst",
                            UiColorSchemeId = new Guid("33333333-cccc-4ccc-8ccc-333333333333")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-8444-444444444444"),
                            Background = "src/assets/images/deep-sea.png",
                            EventColorSchemeId = new Guid("44444444-bbbb-4bbb-8bbb-444444444444"),
                            Name = "Deep Sea",
                            UiColorSchemeId = new Guid("44444444-dddd-4ddd-8ddd-444444444444")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-4555-8555-555555555555"),
                            Background = "src/assets/images/desert.png",
                            EventColorSchemeId = new Guid("55555555-cccc-4ccc-8ccc-555555555555"),
                            Name = "Desert Earth",
                            UiColorSchemeId = new Guid("55555555-eeee-4eee-8eee-555555555555")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-4666-8666-666666666666"),
                            Background = "src/assets/images/flame.png",
                            EventColorSchemeId = new Guid("66666666-dddd-4ddd-8ddd-666666666666"),
                            Name = "Molten Flame",
                            UiColorSchemeId = new Guid("66666666-ffff-4fff-8fff-666666666666")
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-4777-8777-777777777777"),
                            Background = "src/assets/images/flowerpots.png",
                            EventColorSchemeId = new Guid("77777777-eeee-4eee-8eee-777777777777"),
                            Name = "Indoor Jungle",
                            UiColorSchemeId = new Guid("77777777-aaaa-4aaa-8aaa-777777777777")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-4888-8888-188888888888"),
                            Background = "src/assets/images/micro.png",
                            EventColorSchemeId = new Guid("88888888-eeee-4eee-8eee-888888888222"),
                            Name = "Micro Cosmos",
                            UiColorSchemeId = new Guid("88888888-aaaa-4aaa-8aaa-888888888111")
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-4999-9999-199999999999"),
                            Background = "src/assets/images/silk.png",
                            EventColorSchemeId = new Guid("99999999-ffff-4fff-8fff-999999999222"),
                            Name = "Silk Waves",
                            UiColorSchemeId = new Guid("99999999-bbbb-4bbb-8bbb-999999999111")
                        },
                        new
                        {
                            Id = new Guid("aaaa0000-aaaa-4aaa-8aaa-a00000000000"),
                            Background = "src/assets/images/swirl-art.png",
                            EventColorSchemeId = new Guid("aaaa0000-dddd-4ddd-8ddd-a00000000022"),
                            Name = "Warm Swirl",
                            UiColorSchemeId = new Guid("aaaa0000-cccc-4ccc-8ccc-a00000000011")
                        },
                        new
                        {
                            Id = new Guid("bbbb0000-bbbb-4bbb-8bbb-b00000000000"),
                            Background = "src/assets/images/leaf.png",
                            EventColorSchemeId = new Guid("bbbb0000-dddd-4ddd-8ddd-b00000000022"),
                            Name = "Deep Leaf",
                            UiColorSchemeId = new Guid("bbbb0000-cccc-4ccc-8ccc-b00000000011")
                        },
                        new
                        {
                            Id = new Guid("cccc0000-1111-4111-8111-000000000001"),
                            Background = "src/assets/images/light-mode.png",
                            EventColorSchemeId = new Guid("cccc0000-eeee-4eee-8eee-000000000111"),
                            Name = "Light Mode",
                            UiColorSchemeId = new Guid("cccc0000-aaaa-4aaa-8aaa-000000000011")
                        },
                        new
                        {
                            Id = new Guid("dddd0000-2222-4222-8222-000000000002"),
                            Background = "src/assets/images/dark-mode.png",
                            EventColorSchemeId = new Guid("dddd0000-ffff-4fff-8fff-000000000222"),
                            Name = "Dark Mode",
                            UiColorSchemeId = new Guid("dddd0000-bbbb-4bbb-8bbb-000000000022")
                        });
                });

            modelBuilder.Entity("Canalog.Domain.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OptionsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OptionsId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Canalog.Domain.Models.Event", b =>
                {
                    b.HasOne("Canalog.Domain.User", "User")
                        .WithMany("Events")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Canalog.Domain.Options", b =>
                {
                    b.HasOne("Canalog.Domain.Theme", "Theme")
                        .WithMany()
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("Canalog.Domain.Theme", b =>
                {
                    b.HasOne("Canalog.Domain.Models.EventColorScheme", "EventColorScheme")
                        .WithMany()
                        .HasForeignKey("EventColorSchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Canalog.Domain.Models.UiColorScheme", "UiColorScheme")
                        .WithMany()
                        .HasForeignKey("UiColorSchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventColorScheme");

                    b.Navigation("UiColorScheme");
                });

            modelBuilder.Entity("Canalog.Domain.User", b =>
                {
                    b.HasOne("Canalog.Domain.Options", "Options")
                        .WithOne("User")
                        .HasForeignKey("Canalog.Domain.User", "OptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Options");
                });

            modelBuilder.Entity("Canalog.Domain.Options", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Canalog.Domain.User", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
